# Generated by Django 6.0.6 on 2026-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="creado_el",
            new_name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="precio",
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ACEITE", "Aceite / Lubricante"),
                    ("GRASA", "Grasas"),
                    ("QUIMICO", "Aditivos y Químicos (SQ / Tratauto)"),
                    ("ACCESORIO", "Accesorios (Cepillos, etc.)"),
                    ("REPUESTO", "Pastillas y Frenos"),
                ],
                default="ACEITE",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_compra",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Precio de Costo (P.UNIT)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Precio de Venta ($ TOTAL DÓLAR)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="ubicacion_estante",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Ubicación (Ej: Estante 7, Carrito)",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="vendidos",
            field=models.IntegerField(default=0, verbose_name="Unidades Vendidas"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código de Barras",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(
                default="", max_length=150, verbose_name="Descripción del Producto"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(
                default=0, verbose_name="Cantidad en Inventario (CANTIDAD)"
            ),
        ),
    ]
